version: "3.5"

services:
    simple-web:
        image: devopsdockeruh/simple-web-service
        build: .
        ports: 
            - 8080:8080 
        command: server
        container_name: simple-web
