version: "3.5"

services:
    backend: 
        build: ./example-backend
        ports: 
            - 8080:8080
        container_name: backend
    frontend:
        build: ./example-frontend
        ports:
            - 5000:5000
        container_name: frontend
