version: "3.5"

services:
    redis:
        image: redis
        restart: unless-stopped
        container_name: redis

    backend: 
        build: ./example-backend
        environment:
            REDIS_HOST: redis
        depends_on:
            - redis
        ports: 
            - 8080:8080
        container_name: backend

    frontend:
        build: ./example-frontend
        depends_on:
            - backend
        ports:
            - 5000:5000
        container_name: frontend
