version: "3.5"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        container_name: postgres

    redis:
        image: redis
        restart: unless-stopped
        container_name: redis

    backend: 
        build: ./example-backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres
        ports: 
            - 8080:8080
        container_name: backend

    frontend:
        build: ./example-frontend
        depends_on:
            - backend
        ports:
            - 5000:5000
        container_name: frontend

   

