version: "3.5"

services:
    ml-training:
        build: ./ml-kurkkumopo-training
        volumes:
            - model:/src/model
            - imgs:/src/imgs
            - data:/src/data
        container_name: ml-training

    ml-backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes:
            - model:/src/model
        depends_on:
            - ml-training
        container_name: ml-backend

    ml-frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
        container_name: ml-frontend

volumes:
    model:
    imgs:
    data:
